### ISSUE TITLE
Plan, TODO and Not TODO

### ISSUE THREAD

**Issue by tmtk75** [memodify/memodify.github.io#1]
# Application
## Functional specs
* Noting
  * [x] 🗒️ Simple CRUD of notes.
  * [x] Filter notes with texts.
  * [x] ⭐ Star notes.
  * [x] ❤️ Like notes.
* 🏷️ Label management
  * [x] CRUD of labels, apply labels to notes.
  * [x] Filter notes with labels.
* Role management
  * [x] CRUD of roles, apply role to notes.
  * [x] Filter notes with role.
* [x] Search notes with free texts using lunr.
* Authentication
  * [x] Authentication with Auth0 connecting to GitHub.
  * [x] Retrieve OAuth2 access token for Dropbox with NextAuth.js.
  * ~[ ] Upgrade NextAuth.js to v4.~ depends on https://github.com/nextauthjs/next-auth/discussions/3945
* Backup
  * [x] Synchronize locally with CouchDB and PouchDB.
* Editor
  * [x] Simple Markdown editor with monaco-editor
  * [x] Support MDX. https://mdxjs.com/
  * [x] Support KaTeX
  * ~[ ] Support mermaid~ (pending)
  * [x] Attachments by DnD & paste
* [x] Undo/Redo
* [x] Shortcut
* Navigation
  - [x] Guard when dirty
  - pending ~[ ] Backup & restore unfinished content~
* [x] Command Palette
  - [x] Fuzzy match
* [x] Zen mode

## UI
* [x] Basic styling.

## Non functional specs
* [x] Build .dmg with electron-builder.
* [x] 🚢 Shipping to GitHub release of private repository.
* [x] Auto update with electron-autoupdater.

## Test cases
* [x] Basic component tests with Jest.
* ~[ ] Dark mode.~ tough to test dark mode (not sure of why I added 😅 )

# Infrastructure
* [x] Domain acquisition.
* [x] Deployment on vercel by pushing. Preview, promotion to production.

# Web sites
https://www.memodify.com/
* [x] Deployment by pushing
* [x] Make a content
* [x] Google Analytics 

# Branding
* pending ~[ ] Create a logo~ pending

# Not TODO
Probably I won't to do these.
* Mobile application. There are good applications and I'm not interested so much.
* Data synchronization remotely. Memodify is totally private standalone use.
* Plugin/Add-ons mechanism. It easily causes vulnerabilities.
* Share features. Memodify is designed for personal and private data.
