### ISSUE TITLE
TODO to release

### ISSUE THREAD

**Issue by tmtk75** [memodify/memodify.github.io#2]
# Application
* [x] preview: Refine attachment list.
* [x] preview: Enable to download attachments.
* [x] note: Sample for supported GFM notations.
* [x] note: Sample for full extensions like MDX, Math expr by KaTeX, etc.
* [x] role: A ~few~ role~s~ with color.
* [x] label: Some labels with color.
* [x] label: Refine page when no labels.
* [x] preview: Refine "Try again" when it fails to evaluate given mdx.
* [x] preview: Refine plugins for mdast and rehype.
* [x] footer: Refine feedback link.
* [x] settings: Refine items.
* [x] Save as file by CTRL + S if it's a note associated with a file.

# Web site
https://www.memodify.com/
* [x] Replace the cover image.
* [x] Section for feature list.
* [x] Section for feature list more.
* [x] Locate sample data somewhere to be imported. <https://memodify.com/memodify-manual.json.zip>
* [x] ogp tags

# Branding
* [x] Application icon v1
* [x] Favicon

# Manual & user guide
* [x] Guide to load sample.
